# Generated by Django 3.0.6 on 2020-05-24 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user_address', models.CharField(max_length=100)),
                ('national_id', models.FileField(upload_to='documents/national_ids')),
                ('birth_certificate', models.FileField(upload_to='documents/birth_certificates')),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('accademic_level', models.CharField(default='year1', max_length=10)),
                ('expected_completion_date', models.DateField()),
                ('moltivation', models.TextField(verbose_name='Why do you deserve sponsorship? ')),
                ('recommendation_letter', models.FileField(upload_to='documents/recommendation_letters')),
                ('status', models.CharField(default='pending', max_length=30)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_date', models.DateTimeField(null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
