# Generated by Django 3.0.6 on 2020-05-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_sponsored',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
