# Generated by Django 3.0.6 on 2020-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200524_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approval_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
