# Generated by Django 3.0.6 on 2020-05-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200524_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accademic_level',
            field=models.CharField(choices=[('year1', 'Year 1'), ('year2', 'Year 2'), ('year3', 'Year 3'), ('year4', 'Year 4'), ('year4', 'Year 5')], default='year1', max_length=10, verbose_name='Academic Level'),
        ),
    ]
